

-- CREAR BASE DE DATOS
-- IF NOT EXISTS: ES OPCIONAL Y GARANTIZA QUE NO OCURRA UN ERROR SI EXISTE LA BASE DE DATOS
CREATE DATABASE IF NOT EXISTS autosEducacionIT;

-- USAR UNA BASE DE DATOS
USE autosEducacionIT;

-- CREAR UNA TABLA CON CAMPOS Y CLAVE PRIMARIA
CREATE TABLE IF NOT EXISTS autoFamiliar (
	patenteNumero 	VARCHAR(15),
	patenteActiva 	BOOLEAN DEFAULT 1,
	marca 			VARCHAR(100) NOT NULL,
	categoria 		VARCHAR(100) NOT NULL,
	color 			VARCHAR(50),
	puestos 		INT,
	PRIMARY KEY(patenteNumero)
);

