-- USAR BASE DE DATOS
USE autosEducacionIT;

-- BORRAR TODOS LOS REGISTROS, NO RECOMENDADO SIEMPRE SE DEBE ESPECIFICAR QUE REGISTROS ACTUALIZAR
DELETE FROM autoFamiliar;

-- ACTUALIZAR LOS REGISTROS QUE SE ESPECIFICAN
DELETE FROM autoFamiliar
WHERE patenteActiva <> 0;

